<?php
/**
 * * Template Name: Contact Template

 * The template for displaying all pages.
 *
 * This is the template that displays all pages by default.
 * Please note that this is the WordPress construct of pages and that other
 * 'pages' on your WordPress site will use a different template.
 *
 * @package WordPress
 * @subpackage Twenty_Thirteen
 * @since Twenty Thirteen 1.0
 */

get_header(); ?>

<div class="wrapper canpad">
	<?php get_sidebar(); ?>
    <div class="canrgt">
		<?php while ( have_posts() ) : the_post(); 
			//the_content();
		?>
		
		
		<!-- Generated by responder.co.il -->
<script type="text/javascript">
<!--
function responder_validation(form) {
	var inputs = form.getElementsByTagName('input');
	var selects = form.getElementsByTagName('select');
	var filter_email = /^([\w\!\#$\%\&\'\*\+\-\/\=\?\^\`{\|\}\~]+\.)*[\w\!\#$\%\&\'\*\+\-\/\=\?\^\`{\|\}\~]+@((((([a-z0-9]{1}[a-z0-9\-]{0,62}[a-z0-9]{1})|[a-z])\.)+[a-z]{2,6})|(\d{1,3}\.){3}\d{1,3}(\:\d{1,5})?)$/i;
	var filter_phone = /^(?:|(?:050|052|053|054|055|057|058|02|03|04|08|09)\d{7,7})$/;

	for (a=0; a<inputs.length; a++) {
		switch (inputs[a].name) {
			case 'fields[subscribers_email]':
				if (!filter_email.test(inputs[a].value)) {
					alert('כתובת הדוא"ל אינה חוקית');
					inputs[a].focus();
					return false;
				}

				break;
			case 'fields[subscribers_phone]':
				var phone = inputs[a].value.replace(/-|\s/g, '');
				if (!filter_phone.test(phone.length==0 || phone.charAt(0)=='0' ? phone : '0' + phone)) {
					alert('מספר הטלפון הנייד אינו חוקי');
					inputs[a].focus();
					return false;
				}

				break;
			case 'fields[subscribers_name]':
				if (inputs[a].value.replace(/^\s+|\s+$/g, '')=='') {
					alert('נא לרשום שם');
					inputs[a].focus();
					return false;
				}

				break;
			case 'fields[טלפון]':
				if (inputs[a].value.replace(/^\s+|\s+$/g, '')=='') {
					alert('נא לרשום טלפון');
					inputs[a].focus();
					return false;
				}

				break;
		}
	}

	for (a=0; a<selects.length; a++) {
		switch (selects[a].name) {
		}
	}

	if (document.charset)
		form.encoding.value = document.charset;
	else if (document.defaultCharset)
		form.encoding.value = document.defaultCharset;
	else if (document.characterSet)
		form.encoding.value = document.characterSet;

	return true;
}
//-->
</script>
<div class="dgray17" style="margin-bottom:30px;"><?php the_content(); ?></div> 
<form method="post" action="https://subscribe.responder.co.il/subscribe.php" onsubmit="return responder_validation(this);">
<table border="0" dir="rtl">
	<tbody>
		<tr>
			<td><input type="text" name="fields[subscribers_email]" size="14" dir="rtl" class='oalin' placeholder="דואר אלקטרוני" /></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
		</tr>
		<tr>
			
			<td><input type="text" name="fields[subscribers_name]" size="14" dir="rtl" class='oalin' placeholder='שם' /></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
		</tr>
		<tr>
			
			<td><input type="text" name="fields[טלפון]" size="14" dir="rtl" class='oalin' placeholder="טלפון" /></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td><textarea name="fields[הערות]" rows="5" cols="60" size="14" dir="rtl" class='oalin-textarea' placeholder="הערות"></textarea></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
		</tr>
		<tr>
			<td colspan="2" >
				<input type="hidden" name="form_id" value="733" />
				<input type="hidden" name="encoding" value="" />
				<input type="submit" value="שלח" class='oalbtn-contact' />
			</td>
		</tr>
	</tbody>
</table>
</form>

		
		
		
		<?php
			
			
			
			
			wp_link_pages( array( 'before' => '<div class="page-links"><span class="page-links-title">' . __( 'Pages:', 'twentythirteen' ) . '</span>', 'after' => '</div>', 'link_before' => '<span>', 'link_after' => '</span>' ) ); ?>
			<footer class="entry-meta">
				<?php edit_post_link( __( 'Edit', 'twentythirteen' ), '<span class="edit-link">', '</span>' ); ?>
			</footer>
		<?php endwhile; ?>
</div>
<div class="clear"></div>
</div>
<?php get_footer(); ?>