<!-- Generated by responder.co.il -->
<script type="text/javascript">
<!--
function responder_validation(form) {
	var inputs = form.getElementsByTagName('input');
	var selects = form.getElementsByTagName('select');
	var filter_email = /^([\w\!\#$\%\&\'\*\+\-\/\=\?\^\`{\|\}\~]+\.)*[\w\!\#$\%\&\'\*\+\-\/\=\?\^\`{\|\}\~]+@((((([a-z0-9]{1}[a-z0-9\-]{0,62}[a-z0-9]{1})|[a-z])\.)+[a-z]{2,6})|(\d{1,3}\.){3}\d{1,3}(\:\d{1,5})?)$/i;
	var filter_phone = /^(?:|(?:050|052|053|054|055|057|058|02|03|04|08|09)\d{7,7})$/;

	for (a=0; a<inputs.length; a++) {
		switch (inputs[a].name) {
			case 'fields[subscribers_email]':
				if (!filter_email.test(inputs[a].value)) {
					alert('כתובת הדוא"ל אינה חוקית');
					inputs[a].focus();
					return false;
				}

				break;
			case 'fields[subscribers_phone]':
				var phone = inputs[a].value.replace(/-|\s/g, '');
				if (!filter_phone.test(phone.length==0 || phone.charAt(0)=='0' ? phone : '0' + phone)) {
					alert('מספר הטלפון הנייד אינו חוקי');
					inputs[a].focus();
					return false;
				}

				break;
		}
	}

	for (a=0; a<selects.length; a++) {
		switch (selects[a].name) {
		}
	}

	if (document.charset)
		form.encoding.value = document.charset;
	else if (document.defaultCharset)
		form.encoding.value = document.defaultCharset;
	else if (document.characterSet)
		form.encoding.value = document.characterSet;

	return true;
}
//-->
</script>
<?php 
global $template;
$page_template = basename($template);

	if($_SESSION['form_id']){
		$_SESSION['form_id'] = $_SESSION['form_id'] + 1;
	}
	else{
		$_SESSION['form_id'] = 1;
	}
	
if(is_front_page() || $page_template == 'index.php'){
	$form_id = 'home_form_' . $_SESSION['form_id'];
}
else if($page_template == 'price.php'){
	$form_id = 'price_form';
}
else if($page_template == 'can.php'){
	$form_id = 'can_form';
}
else{
	$form_id = 'Other';
}
?>
<form method="post" action="https://cp.responder.co.il/subscribe.php" onsubmit="return responder_validation(this);">
<table border="0" dir="rtl" class="trial_form form_col">
	<tbody>
		<tr>
			<td><input type="text" name="fields[subscribers_name]" class="oalin" size="14" dir="rtl" placeholder="שם פרטי" /></td>
		</tr>
		<tr>
			<td><input type="text" name="fields[שם משפחה]" class="oalin" size="14" dir="rtl" placeholder="שם משפחה" /></td>
		</tr>
		<tr>
			<td><input type="email" name="fields[subscribers_email]" class="oalin" size="14" dir="rtl" placeholder="דואר אלקטרוני *" oninvalid="setCustomValidity('.נא להזין כתובת דוא״ל תקינה')" /></td>
		</tr>
		<tr>
			<td><input type="hidden" name="fields[מקור]" size="14" dir="rtl" placeholder="" /></td>
		</tr>
		<tr>
			<td><input type="hidden" name="fields[טופס]" size="14" dir="rtl" value="<?php echo $form_id; ?>" placeholder="" /></td>
		</tr>
		<tr>
			<td>
				<input type="hidden" name="form_id" value="5403" />
				<input type="hidden" name="encoding" value="" />
				<input type="submit" class="oalbtn" value="פתח חשבון התנסות" />
			</td>
		</tr>
	</tbody>
</table>
</form>
